<img src="./static/aeropython_name_mini.png" alt="AeroPython" style="width: 300px;"/>

# Taller Aeropython de Introducción

## Parte 4: Importar bibliotecas y algunos ejemplos de Python de Verdad

### ¿Qué es una biblioteca?

A parte de un sitio con libros al que la gente iba a leer antes de que existiera Internet, las bibliotecas o librerías (del inglés library) tienen otro significado: 
<div class="alert alert-info"><strong>Tip</strong>:
Una biblioteca es un conjunto de funciones y objetos que se distribuyen en bloque y que permiten expandir las funciones del Python básico en un campo concreto.
</div>

[<img src="./static/XKCDpython.png" alt="AeroPython" style="width: 400px;"/>](https://xkcd.com/353/)

#### Ejemplo: Numpy

Una de las bibliotecas de Python más conocidas es Numpy. Numpy añade un tipo de objeto nuevo: el Array, y numerosas funciones matemáticas para interactuar con ellos. Un array es parecido a una lista (o una lista de listas), y es el equivalente a los vectores y matrices de las matemáticas en papel. Gracias a una serie de técnicas más o menos complejas, las operaciones matemáticas con arrays son mucho más sencillas y rápidas que trabajar con los tipos básicos.

In [1]:
# Para poder usar una biblioteca, tenemos que añadir sus funciones y objetos
# al proyecto que estemos creando. Esto se llama "importarla".
import numpy #Así de fácil

Ahora, podemos usar todas las funciones y objetos de numpy. Para llamarlas, se hace así:

In [2]:
x = [[ 0, 1],
       [ 2, 3]] # x es una lista de listas
y = numpy.array(x) # la función array convierte la lista en un objeto array
y

array([[0, 1],
       [2, 3]])

Comprobemos si es tan rápido como dicen!

In [24]:
#vamos a crear una matriz horrorosa!
x = []
for ii in range(1000):
    sub_matriz = []
    for jj in range(1000):
        sub_matriz.append(ii + 1000 * jj)
    x.append(sub_matriz)


In [25]:
y = numpy.array(x)
y # es un array que contiene lo mismo que x

array([[     0,   1000,   2000, ..., 997000, 998000, 999000],
       [     1,   1001,   2001, ..., 997001, 998001, 999001],
       [     2,   1002,   2002, ..., 997002, 998002, 999002],
       ..., 
       [   997,   1997,   2997, ..., 997997, 998997, 999997],
       [   998,   1998,   2998, ..., 997998, 998998, 999998],
       [   999,   1999,   2999, ..., 997999, 998999, 999999]])

In [26]:
%%timeit
#Vamos a hacer un truco de magia negra para cronometrar
suma = 0
for fila in x:
    suma += sum(fila)
suma

100 loops, best of 3: 12.3 ms per loop


In [27]:
%%timeit
numpy.sum(y)

1000 loops, best of 3: 565 µs per loop


Numpy tiene muchísimas funciones útiles para trabajar con matemáticas, vectores y matrices:

In [56]:
M = numpy.random.randint(20,size = (4,4))
#M = numpy.reshape(a, [4,4])
M

array([[12, 16,  5, 15],
       [19, 13, 10, 14],
       [12, 10,  0, 17],
       [ 6, 14, 12, 16]])

In [57]:
M.T

array([[12, 19, 12,  6],
       [16, 13, 10, 14],
       [ 5, 10,  0, 12],
       [15, 14, 17, 16]])

In [62]:
M + M.T

array([[24, 35, 17, 21],
       [35, 26, 20, 28],
       [17, 20,  0, 29],
       [21, 28, 29, 32]])

In [58]:
M @ M.T

array([[650, 696, 559, 596],
       [696, 826, 596, 640],
       [559, 596, 533, 484],
       [596, 640, 484, 632]])

In [59]:
numpy.linalg.inv(M)

array([[-0.01387684,  0.07762359,  0.00375831, -0.05890431],
       [ 0.19947962, -0.05333912, -0.0956924 , -0.03866724],
       [-0.08239376,  0.05464007, -0.04018502,  0.07213067],
       [-0.10754553, -0.02341717,  0.11246025,  0.06432495]])

In [61]:
(M @ numpy.linalg.inv(M)).round(3)

array([[ 1.,  0.,  0.,  0.],
       [-0.,  1.,  0.,  0.],
       [-0.,  0.,  1.,  0.],
       [-0.,  0.,  0.,  1.]])

##### Ejercicio 2- Creador de contraseñas

Se desea programar un generador de contraseñas que sean fáciles de recordar gracias a estar basadas en palabras, pero que sean inmunes a [ataques de diccionario](https://es.wikipedia.org/wiki/Ataque_de_diccionario)

Para ello, usaremos un algoritmo ultramoderno llamado [Cifrado César](https://es.wikipedia.org/wiki/Cifrado_C%C3%A9sar). Este nombre se puso en honor a uno de sus usuarios más conocidos, Julio César, que lo usaba para mandar cartas a sus generales.

###### Instrucciones:

El cifrado César es un cifrado de sustitución por desplazamiento. Esto quiere decir que el mensaje (en este caso, la contraseña) se descompone en letras, y cada una de ellas es sustituída por otra mediante un desplazamiento en el abecedario.
<img src="./static/cifrado_cesar.png" alt="Ejemplo de cifrado César" style="width: 300px;"/>

###### Objetivo:

Escribe una función en Python que calcule e imprima por pantalla la codificación de una frase o palabra cualquiera, que pueda incluír espacios y números. El número de puestos que se desplazan debe ser un argumento de entrada de la función. Los acentos y la ñ pueden incluírse o no.

Después comprueba el algoritmo con las siguientes frases:
- "Benjamín pidió 3 bebidas de kiwi y fresa. Noé, sin vergüenza, las 8 más exquisitas champañas del menú" - Desplazamiento = 4
- "José compró en Perú 7 viejas zampoñas. Excusándose, Sofía tiró su whisky al desagüe de la banqueta." - Desplazamiento = 10

Si te está gustando este taller:

<a href="https://twitter.com/share" class="twitter-share-button" data-url="https://github.com/AeroPython/PyDayMad16-intro" data-text="Aprendiendo Python con" data-via="AeroPython" data-lang="es" data-size="large" data-hashtags="PyDay">Twittear</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

#### <h4 align="right">¡Síguenos en Twitter!

###### <a href="https://twitter.com/AeroPython" class="twitter-follow-button" data-show-count="false">Follow @AeroPython</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>  

##### <a rel="license" href="http://creativecommons.org/licenses/by/4.0/deed.es"><img alt="Licencia Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Curso AeroPython</span> por <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Juan Luis Cano Rodriguez y Alejandro Sáez Mollejo</span> se distribuye bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/deed.es">Licencia Creative Commons Atribución 4.0 Internacional</a>.

##### <script src="//platform.linkedin.com/in.js" type="text/javascript"></script> <script type="IN/MemberProfile" data-id="http://es.linkedin.com/in/juanluiscanor" data-format="inline" data-related="false"></script> <script src="//platform.linkedin.com/in.js" type="text/javascript"></script> <script type="IN/MemberProfile" data-id="http://es.linkedin.com/in/alejandrosaezm" data-format="inline" data-related="false"></script>

---
_Las siguientes celdas contienen configuración del Notebook_

_Para visualizar y utlizar los enlaces a Twitter el notebook debe ejecutarse como [seguro](http://ipython.org/ipython-doc/dev/notebook/security.html)_

    File > Trusted Notebook

In [1]:
%%html
<a href="https://twitter.com/AeroPython" class="twitter-follow-button" data-show-count="false">Follow @AeroPython</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

In [4]:
# Esta celda da el estilo al notebook
from IPython.core.display import HTML
css_file = './static/style.css'
HTML(open(css_file, "r").read())